# Site settings
title: Advanced Timing with the Crab Pulsar 
description: This site contains the notebooks we used to extract TOAs and run PINT to develop our timing solution. 
url: "https://samikris.github.io/AAS224-advancedtiming/"

# Build settings
theme: minimal # Replace 'minima' with your desired theme
markdown: kramdown

# Optional settings
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude files from processing
exclude:
  - Gemfile
  - Gemfile.lock
