# Site settings
title: Advanced Timing with the Crab Pulsar 
description: This site contains the notebooks we used to extract TOAs and run PINT to develop our timing solution. 
url: "https://samikris.github.io/AAS224-advancedtiming/"

# Build settings
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
#smarkdown: kramdown

# Optional settings
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude files from processing
exclude:
  - Gemfile
  - Gemfile.lock
